# Prometheus configuration for Universal Translator Pro
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    cluster: 'universal-translator'
    environment: 'production'

# Rule files
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 15s

  # Universal Translator API
  - job_name: 'universal-translator-api'
    static_configs:
      - targets: ['api:9090']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']
    metric_relabel_configs:
      # Add service label
      - source_labels: [__name__]
        target_label: service
        replacement: 'universal-translator-api'
      
      # Add version label if available
      - source_labels: [version]
        target_label: app_version
        regex: '(.*)'
        replacement: '${1}'

  # PostgreSQL metrics
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    scrape_timeout: 10s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics

  # Application health checks
  - job_name: 'universal-translator-health'
    static_configs:
      - targets: ['api:8080']
    metrics_path: /health/metrics
    scrape_interval: 30s
    scrape_timeout: 10s
    params:
      format: ['prometheus']

# Remote write configuration for long-term storage
remote_write:
  - url: "https://prometheus-prod.monitoring.yourdomain.com/api/v1/write"
    basic_auth:
      username: "prometheus"
      password: "your-remote-write-password"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 10
      capacity: 10000

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 50GB
    wal-compression: true